// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSTrCscFERhOSTyf2zGov8jMddLmwv1o',
    appId: '1:117949893379:web:f09837353607f6f728f736',
    messagingSenderId: '117949893379',
    projectId: 'jambu-217b5',
    authDomain: 'jambu-217b5.firebaseapp.com',
    storageBucket: 'jambu-217b5.firebasestorage.app',
    measurementId: 'G-H0PMPD98M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeOgHoCH3moXfsu2o_mOQjULjNFO81RN4',
    appId: '1:117949893379:android:c18f87ff8c1f292f28f736',
    messagingSenderId: '117949893379',
    projectId: 'jambu-217b5',
    storageBucket: 'jambu-217b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9krp8qnSV9eR2cbViu2H4XPRF4AyfW4',
    appId: '1:117949893379:ios:df2955284a65eca928f736',
    messagingSenderId: '117949893379',
    projectId: 'jambu-217b5',
    storageBucket: 'jambu-217b5.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9krp8qnSV9eR2cbViu2H4XPRF4AyfW4',
    appId: '1:117949893379:ios:df2955284a65eca928f736',
    messagingSenderId: '117949893379',
    projectId: 'jambu-217b5',
    storageBucket: 'jambu-217b5.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeSTrCscFERhOSTyf2zGov8jMddLmwv1o',
    appId: '1:117949893379:web:7397cddb4d5d20f428f736',
    messagingSenderId: '117949893379',
    projectId: 'jambu-217b5',
    authDomain: 'jambu-217b5.firebaseapp.com',
    storageBucket: 'jambu-217b5.firebasestorage.app',
    measurementId: 'G-B9N0P3F9KG',
  );
}
